services:
  - type: web
    name: iclass-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    
    # Additional system packages needed for OpenCV and Tesseract
    buildFilter:
      paths:
        - requirements.txt
      ignoredPaths:
        - .git/**
    preInstallCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-chi-sim libgl1-mesa-glx libglib2.0-0 